import Head from "next/head";
import styles from "@/styles/LandingPage.module.css";

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
	  <div className="container">
	  	<header>
			<h2>Title App</h2>
			<nav>
				
			</nav>
		</header>
	  </div>
    </>
  );
}
